<Project>
  <PropertyGroup>
    <Version>10.0.0-rc00</Version>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
    <FxNugetVersion Condition=" '$(TargetFramework)' == 'net6.0' ">6.0.0</FxNugetVersion>
    <FxNugetVersion Condition=" '$(TargetFramework)' == 'net7.0' ">7.0.0</FxNugetVersion>
    <FxNugetVersion Condition=" '$(TargetFramework)' == 'net8.0' ">8.0.0</FxNugetVersion>
    <FxNugetVersion Condition=" '$(TargetFramework)' == 'net10.0' ">10.0.0</FxNugetVersion>
    <FxNugetVersion Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">3.1.16</FxNugetVersion>
    <NCoreUtilsProtocolVersion>10.0.0-rc00</NCoreUtilsProtocolVersion>
    <NCoreUtilsDataVersion>10.0.0-rc00</NCoreUtilsDataVersion>
  </PropertyGroup>
</Project>
