<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0</TargetFrameworks>
    <RootNamespace>NCoreUtils.Rest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.Data.Abstractions" Version="$(NCoreUtilsDataVersion)" />
    <PackageReference Include="NCoreUtils.Data.Protocol.Client.Abstractions" Version="$(NCoreUtilsProtocolVersion)" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
