<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>NCoreUtils.AspNetCore.Rest</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>
  <!-- NOTE: NET Standard polyfill -->
  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">
    <Compile Include="..\shared\CompilerServices\**" />
  </ItemGroup>
  <!-- NOTE: Common -->
  <ItemGroup>
    <Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.Data.Abstractions" Version="$(NCoreUtilsDataVersion)" />
    <PackageReference Include="NCoreUtils.Extensions.Collections" Version="10.0.0" />
    <PackageReference Include="NCoreUtils.Extensions.Preconditions" Version="10.0.0.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.1' ">
    <Compile Remove="CodeAnalysis\**" />
  </ItemGroup>
</Project>
